### ISSUE TITLE
Issue with tutorials/run-wordpress-on-appengine-standard/index.md

### ISSUE THREAD

**Issue by tomnunn** [GoogleCloudPlatform/community#1186]
Is it worth extending this tutorial to include an explanation of how to exclude `index.php` from URL/s? This seems to be quite a commonly asked question from what I can see when searching around and struggling to find/understand a solution for php72 runtime configuration.

**Comment by ToddKopriva** [comment]
@bshaffer , I'm tagging you so that you can see this request about a tutorial that you authored.

**Comment by bshaffer** [comment]
@tomnunn I haven't run into this issue, can you go to `Settings > Permalink` and make sure that `index.php` is not written in your custom structure? Is this happening after you've deployed to App Engine, or is it just locally?

**Comment by tomnunn** [comment]
@bshaffer No, unfortunately not. I've attached a couple of screenshots of WP Admin to show how the Permalink settings are being displayed. I've never seen the `index.php` in the example URLs before like they are showing at the moment.

https://i.imgur.com/Nd2tgBS.png
https://i.imgur.com/vkK5sHz.png

I saw there is some documentation around simulating Apache mod_rewrite routing, although it's referenced on a php55 runtime and at the bottom of the explanation it states to avoid the need to use mod_reqrite and displays a snippet, which looks like we are handling this in `gae-app.php` (i.e `@parse_url($full_request_uri)['path']`):

```php
/**
 * Function to return a PHP file to load based on the request URI.
 *
 * @param string $full_request_uri The request URI derivded from $_SERVER['REQUEST_URI'].
 */
function get_real_file_to_load($full_request_uri)
{
    $request_uri = @parse_url($full_request_uri)['path'];

    // Redirect /wp-admin to /wp-admin/ (adds a trailing slash)
    if ($request_uri === '/wp-admin') {
        header('Location: /wp-admin/');
        exit;
    }

    // Serve up "index.php" when /wp-admin/ is requested
    if ($request_uri === '/wp-admin/') {
        return '/wp-admin/index.php';
    }

    // Load the file requested if it exists
    if (is_file(__DIR__ . $request_uri)) {
        return $request_uri;
    }

    // Send everything else through index.php
    return '/index.php';
}
```

**Comment by tomnunn** [comment]
app.yaml
```yaml
# App Engine runtime configuration
runtime: php73

# 
service: example-service

# Defaults to "serve index.php" and "serve public/index.php". Can be used to
# serve a custom PHP front controller (e.g. "serve backend/index.php") or to
# run a long-running PHP script as a worker process (e.g. "php worker.php").
entrypoint: serve gae-app.php

# Defines static handlers to serve WordPress assets
handlers:
- url: /(.*\.(htm|html|css|js))
  static_files: \1
  upload: .*\.(htm|html|css|js)$
  secure: always

- url: /wp-content/(.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg))
  static_files: wp-content/\1
  upload: wp-content/.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg)$
  secure: always

- url: /(.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg))
  static_files: \1
  upload: .*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg)$
  secure: always

- url: /wp-includes/images/media/(.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg))
  static_files: wp-includes/images/media/\1
  upload: wp-includes/images/media/.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg)$
  secure: always

- url: /(.+\.php)$
  script: \1
  secure: always

- url: /.*
  script: index.php
  secure: always
```
