### ISSUE TITLE
Issue with tutorials/appengine-ruby-rails-activejob-sidekiq.md

### ISSUE THREAD

**Issue by xenyal** [GoogleCloudPlatform/community#2035]
The `entrypoint` command specified in `worker.yaml` does not take precedence over the CMD that is declared within a Dockerfile when used with `runtime: custom`.

Dockerfile:
```
FROM ruby:3.0.3-alpine3.15

RUN apk --update --upgrade --no-cache add curl-dev build-base openssh \
    tzdata postgresql-dev

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

RUN gem install bundler

ADD Gemfile* $APP_HOME/

RUN bundle config set --local without 'development test' deployment 'true' && \
    bundle install

COPY . $APP_HOME

EXPOSE 8080

CMD ["irb"]
```

worker.yaml:
```
runtime: custom
env: flex
service: worker

entrypoint: bundle exec sidekiq

liveness_check:
  path: '/health_check'

readiness_check:
  path: '/health_check'

manual_scaling:
  instances: 1
```

I've verified that if I switch the `CMD` args to use `bundle exec sidekiq` instead of `irb`, that the App Engine instance is deployed successfully. However, it seems that the `entrypoint` key that I specify in the app or worker.yaml files are ignored completely. The only command that matters seems to be what's specified in the Dockerfile `CMD`.

I also have the initializer for `sidekiq_alive`, with the port set to `8080`, which shows up in the application logs that I tail via `gcloud app logs tail` when the deployment works - which is absent during the cases where the deployment does not. Might I be missing something ... like an `ENTRYPOINT`, in my Dockerfile?

---

Adding a different test case which demonstrates this issue via the Stack Overflow question I asked:
https://stackoverflow.com/questions/70674640/google-app-engine-flexible-ruby-custom-is-ignoring-entrypoint
