### ISSUE TITLE
Issues with deploy-dependency-track tutorial

### ISSUE THREAD

**Issue by nettrino** [GoogleCloudPlatform/community#2295]
Hello, 

I was following https://cloud.google.com/community/tutorials/deploy-dependency-track and run into the following issues (in order of appearance)

1. `cyclonedx` command failed with a `KeyError` using the version installed in the tutorial so I had to run 
`cyclonedx-py -r -i requirements.txt --format json -o bom.json` (using cyclonedx-python-lib 3.1.1 installed via homebrew on os x m1)
2. Needed to run `gcloud components install gke-gcloud-auth-plugin`
3. Had to modify `api/ingress.yaml` to 
```yaml
apiVersion: networking.k8s.io/v1
...
spec:
  rules:
    - http :
        paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: dependency-track-apiserver-svc
               port: 
                 number: 8088
```
and `frontend/ingress.yaml` to 

```yaml
apiVersion: networking.k8s.io/v1
...
spec:
  rules:
    - http :
        paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: dependency-track-frontend-svc
               port: 
                 number: 8080
```

Any feedback on this latter modification is most welcome, as I am not familiar with k8s enough to be confident that the above change is doing the appropriate things 

--------

Another question I had for this tutorial is the following. Do we *have* to have provisioned TLS certs and corresponding A records or is there a way to try this out directly using the IPs (using the current demo configs, that is).

**Comment by ToddKopriva** [comment]
@dedickinson , can you take a look at these questions about a document that you authored?

**Comment by nettrino** [comment]
Thanks for looking into this @dedickinson  - I also don't seem to be getting reachability into the public IPs which mean something is definitely off.

**Comment by dedickinson** [comment]
Hiya,

Yup, I'll take a look in the coming days. I also plan to refresh the tutorial over the next couple of months.

Regarding the use of TLS, I suppose this is technically possible but I set this out in the tutorial because you're creating a public-facing system that takes usernames/passwords. However, I'll explore the use of Cloud Endpoints to make this a little easier.

Cheers,
Duncan

**Comment by dedickinson** [comment]
RE: needing to run `gcloud components install gke-gcloud-auth-plugin`

This requirement has arisen since the original release of the tutorial and I'll include it in an upcoming update.

For context, see [Deprecated authentication plugin for Kubernetes clients](https://cloud.google.com/kubernetes-engine/docs/deprecations/auth-plugin)

**Comment by dedickinson** [comment]
Re: `cyclonedx` command failed

Agreed, the newer version (3.10.1) has changed the parameters and I'll update this in the tutorial. As a bonus, you don't need to export to `requirements.txt` and can just run 

- For XML: `cyclonedx-py --format xml --poetry`
- For JSON: `cyclonedx-py --format json --poetry`

_I'd note that the version installed in the tutorial (^0.4.3) does work - but it's rather old._

**Comment by dedickinson** [comment]
RE: Ingress config

I'll need to update this to use v1 of the `networking.k8s.io` API. 

There's been a few changes since the beta. For the frontend, the spec looks something like:

```yaml
spec:
  defaultBackend:
    service:
      name: dependency-track-frontend-svc
      port:
        name: web
```
