### ISSUE TITLE
Extended Symfony GAE tutorial with Doctrine2 DBAL configuration

### ISSUE THREAD

**Issue by swiniak** [GoogleCloudPlatform/community#262]
I'd like to request to extend the tutorial at
https://cloud.google.com/community/tutorials/run-symfony-on-appengine-flexible?hl=uk
with configuration for Doctrine2 DBAL to properly connect to Cloud SQL.

**Comment by GermerCarsten** [comment]
I am really stuck at exactly this problem at the moment. I can't get it to run and I can't find any uptodate documentation or a running example-project anywhere.
My question on stackoverflow didn't find me any help so far, either.
[My question at stackexchange explains my current situation in detail](https://stackoverflow.com/questions/47183758/symfony3-on-google-app-engine-flexible-cant-connect-to-google-cloud-sql-mysql)

So, since this requests complexity has been tagged as low, can someone please have a look at this and provide help?

Cheers /Carsten

**Comment by bshaffer** [comment]
Thank you for the heads up! I'll take a look at this and see about adding it to the tutorial.

In general, you should be able to configure doctrine using a PDO socket, similar to the [Laravel Tutorial](https://cloud.google.com/community/tutorials/run-laravel-on-appengine-flexible#set-up-database-sessions), but yes detailed instructions would be a big improvement!

**Comment by GermerCarsten** [comment]
@bshaffer This might not be as easy as I thought it should be...
I found out what was happening and detailed it [over at my question regarding this on stackoverflow](https://stackoverflow.com/questions/47183758/symfony3-on-google-app-engine-flexible-cant-connect-to-google-cloud-sql-mysql/47262693#47262693).

- "App Engine Flex for PHP, doesn't run post-deploy-cmd any more"
- "just use post-install-cmd as a drop-in replacement, unless you need DB connection."
- In effect, as of to date, one can't use anything that utilizes the database within post-install-cmd.

I'll be trying to work around that in the next days with my more complex project, but it won't be elegant...
I'll let you know here.

But, please, don't let that deter you from expanding the tutorials and provide me with a proper way to do Symfony/Doctrine on GAEflexible!

Cheers!

**Comment by bshaffer** [comment]
@GermerCarsten You can definitely run database commands in `post-install-cmd`, why do you think that is not the case?

**Comment by bshaffer** [comment]
Yes, you are right, the `post-install-cmd` takes place at build time, and so does not allow you to utilize a socket connection.

Adding @tmatsuo and @chingor13  to comment, as they are in charge of the PHP runtime and the removal of `post-deploy-cmd`.

**Comment by bshaffer** [comment]
Yes, you are right. The `post-install-cmd` takes place at build time and so does not have access to the DB connection yet.

Adding @tmatsuo and @chingor13 to comment, as they are in charge of the PHP runtime and also the deprecation of `post-deploy-cmd`.

**Comment by tmatsuo** [comment]
Yes, at the time the `post-install-cmd` is executed, the DB connection is not available as of today.

You can instead use our `cloud-tools` to run scripts that need the DB connection.

First, remove any scripts that require the DB connection  from `post-install-cmd`.
Then install `google/cloud-tools` as a dev dependency.
Then deploy, and use `flex_exec` command provided by `google/cloud-tools`

```
$ composer require --dev google/cloud-tools:~0.6.7
$ gcloud app deploy
$ vendor/bin/flex_exec run -- composer run-script symfony-script
```

Please try this and let me know how it goes.

**Comment by tmatsuo** [comment]
Also, let us know if the DB connection is really required for you at the build time (`post-install-cmd`).

**Comment by bshaffer** [comment]
Yes, to @tmatsuo's point, you should only real use case for a DB connection in the deprecated `post-deploy-cmd` is for something like database connections. Your application will be able to start up a DB connection at runtime. See my additions in #294 for instructions.

**Comment by GermerCarsten** [comment]
@tmatsuo @bshaffer Yes, right, I already understood that I can't use a DB-connection at post-install and that post-deploy has been removed.

As for your question, I _can't be sure_ if I need a DB-connection in post-install, it's just the Symfony-standard as of today.

When you create an empty project from scratch via composer and add Doctrine database functionality, installAssets is added(?) to the post-install (or DB-access is added to installAssets?).
_I_ am of course not sure of it's innards... what it exactly does and why.
And, if you build a more complex application and add more functionality like migrations and fixtures it automatically adds even more DB-dependent commands to post-install.
In my case up to a point where even clearCache needs a DB connection and doesn't work in post-install.

I will follow the advice given by @tmatsuo , remove all commands that break because they need a DB-connection and move those over to a script I execute with flex_exec.
I can't see why that shouldn't work and solve my problems and I'll report back here once I know for sure.

It will be well worth it to include these steps in the documentation, as a standard installation of Symfony via composer doesn't work on GAE flexible once some Doctrine gets involved...

Thanks for the help! I will report back the next days.
Cheers /Carsten

**Comment by GermerCarsten** [comment]
@bshaffer I'm really sorry, I followed the [added instructions](https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/run-symfony-on-appengine-flexible/index.md#connect-to-cloudsql-with-doctrine) and that is not working.
When set up according to the instructions it runs fine when running locally with cloud_sql_proxy but not on GAE flexible.
(I have got my try-and-error way to work as [documented here](https://stackoverflow.com/questions/47183758/symfony3-on-google-app-engine-flexible-cant-connect-to-google-cloud-sql-mysql/47262693#47262693).)

Can't you just set up a current Symfony with composer, add an entity, a controller and a view, get that to run both locally via cloud-sql-proxy and on GAE flexible and put that project up here?
People would have to set it up with their own values for database, user, pwd and instance_connection_name, of course, and can after base their own project on that.

**Comment by tmatsuo** [comment]
The reason why we first released the external script (flex_exec), is that, for the DB migration task, we believe it is best to do it with an external script.

Running the DB migration script in `post-install-cmd` is not safe for production, because the deployment after the migration may fail for various reasons (not sufficient quota, etc).

However, we also understand that it is very handy to do that, especially during the development phase. If the PHP community really wants it, we can prioritize implementing it (db connection during the build time).

**Comment by GermerCarsten** [comment]
@tmatsuo I understand that and I am fine with not using post-install and instead using flex_exec for everything I need to do after deployment.
In my last post above I just pointed out that the added instructions do not work with a simple fresh current Symfony with one entity, controller and view added.
I'll be back soon with more info.

Again, the easiest way would be to provide a project of a current Symfony with composer, add an entity, a controller and a view, that to run both locally via cloud-sql-proxy and on GAE flexible.
That would be code that was tested and positively runs, I don't have something like that, yet.

**Comment by bshaffer** [comment]
@GermerCarsten Thank you for your feedback on the tutorial. Will you post here or open a new issue detailing the error you are receiving and what is not working? 

If the `database_host` parameter is set, the socket connection will not work. It's a very frustrating issue. So it's important that `DB_HOST` is not set and `database_host` is empty for the App Engine Flexible environment.

We did not detail setting up a [controller](https://symfony.com/doc/master/bundles/SensioGeneratorBundle/commands/generate_controller.html) / [entity](https://symfony.com/doc/master/bundles/SensioGeneratorBundle/commands/generate_doctrine_entity.html) / [view](https://symfony.com/doc/current/templating.html) because there are a lot of other tutorials out there which focus on this.

**Comment by tmatsuo** [comment]
Is it work if you set 'localhost' to the `database_host`, or does it need to be empty?

**Comment by GermerCarsten** [comment]
The screenshot of `composer.json` you provide is Laravel configuration, not Symfony.

You seem to be doing fine with `gcloud app deploy` where I seem to need to use `gcloud beta app deploy`.

Apart from that I copied the example given in the tutorial to the letter and it works locally via cloud-sql-proxy and does not work when deploying to GAE flexible.

What I am hinting at with my suggestion to have a project with an entity, a controller and a view is, that you might have not tested your tutorial enough... Have a testproject and follow your tutorial to the letter, see if it works?

In the meantime, the following works. It is not pretty, can surely be optimized and I need to comment/uncomment the lines in config.yml when testing locally vs. deploying to GAEflex.
But, at least it works and is the only configuration example I have seen so far that does what it's supposed to.

config.yml
```
# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
#        host: '%database_host%'
#        port: '%database_port%'
        host: ~
        port: ~
        unix_socket: '/cloudsql/MY_CONNECTION_STRING'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
```
app.yaml
```
service: default
runtime: php
env: flex

runtime_config:
  document_root: web

env_variables:
  SYMFONY_ENV: prod
  MYSQL_USER: root
  MYSQL_PASSWORD: MY_PASSWORD
  MYSQL_DSN: mysql:dbname=MY_DATABASE;unix_socket=/cloudsql/MY_CONNECTION_STRING
  WHITELIST_FUNCTIONS: libxml_disable_entity_loader

#[START cloudsql_settings]
# Use the connection name obtained when configuring your Cloud SQL instance.
beta_settings:
    cloud_sql_instances: "MY_CONNECTION_STRING"
#[END cloudsql_settings]
```
parameters.yml
```
parameters:
    database_host: 127.0.0.1
    database_port: 3306
    database_name: MY_DATABASE
    database_user: root
    database_password: MY_PASSWORD
```
I'll use this to go into integrating the setup, migrations, fixtures and the like with `flex_exec` which btw is missing completely from your tutorial.
