### ISSUE TITLE
Issue with using cloudbuild to deploy a NodeJS app to app engine

### ISSUE THREAD

**Issue by mark-de-haan** [GoogleCloudPlatform/community#713]
Hi,

Im having an issue where cloudbuild is infinitely creating deployment jobs.
I have a simple Vue app built with vue-cli3

My configuration:

cloudbuild.yaml:
```yaml
steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
- name: "gcr.io/cloud-builders/gcloud"
  args: ['app', 'deploy']
```

app.yaml
```yaml
runtime: custom
env: flexible
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 4.0
  disk_size_gb: 10
env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
liveness_check:
  initial_delay_sec: 300
readiness_check:
  app_start_timeout_sec: 300
```

package.json
```json
...
"scripts": {
    "serve": "vue-cli-service serve",
    "start": "vue-cli-service serve --mode production",
    "build": "vue-cli-service build",
    "test:unit": "vue-cli-service test:unit",
    "test:e2e": "vue-cli-service test:e2e"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "elasticsearch": "^15.3.1",
    "material-design-icons-iconfont": "^4.0.4",
    "materialize-css": "^1.0.0-rc.2",
    "roboto-fontface": "*",
    "swing": "^3.1.3",
    "vue": "^2.5.22",
    "vue-global-events": "^1.1.0",
    "vue-router": "^3.0.1",
    "vue-swing": "^0.0.10",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.3",
    "@vue/cli-plugin-e2e-nightwatch": "^3.0.3",
    "@vue/cli-plugin-unit-jest": "^3.0.3",
    "@vue/cli-service": "^3.0.3",
    "@vue/test-utils": "^1.0.0-beta.20",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^23.6.0",
    "vue-template-compiler": "^2.5.21"
  },
   ...
  "engines": {
      "node": ">=8.9"
   }
```

The first yarn install step is succesfull but the second step to do an app deploy is restarting the build from the first step after it is done.

Am I missing some configuration or is this a bug in cloudbuild?
